name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
      - name: Chekout repository
      uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.6

      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      - name: Run tests
      run: |
        python -m unittest discover tests

      deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/main'

      steps:
      - name: deploy to server
      run: echo "deploying application..."

